'use client';

import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  Calendar,
  MapPin,
  Users,
  Eye,
  Heart,
  Share2,
  MoreHorizontal,
  Image as ImageIcon,
  Video,
  FileText,
  Star,
} from 'lucide-react';
import Image from 'next/image';
import { motion } from 'framer-motion';

interface Album {
  id: string;
  title: string;
  description: string;
  coverImageUrl?: string;
  theme: 'nature' | 'history' | 'food' | 'culture' | 'general';
  isPublic: boolean;
  isAutoGenerated: boolean;
  itemCount: number;
  viewCount: number;
  likeCount: number;
  createdAt: Date;
  updatedAt: Date;
  items: AlbumItem[];
}

interface AlbumItem {
  id: string;
  type: 'stamp' | 'photo' | 'video' | 'text';
  title: string;
  contentUrl: string;
  thumbnailUrl?: string;
  metadata: any;
}

interface AlbumCardProps {
  album: Album;
  onView?: (album: Album) => void;
  onEdit?: (album: Album) => void;
  onShare?: (album: Album) => void;
  onLike?: (album: Album) => void;
  showActions?: boolean;
}

export default function AlbumCard({
  album,
  onView,
  onEdit,
  onShare,
  onLike,
  showActions = true,
}: AlbumCardProps) {
  const [isHovered, setIsHovered] = useState(false);
  const [isLiked, setIsLiked] = useState(false);

  const getThemeColor = (theme: string) => {
    switch (theme) {
      case 'nature':
        return 'bg-green-100 text-green-800';
      case 'history':
        return 'bg-purple-100 text-purple-800';
      case 'food':
        return 'bg-orange-100 text-orange-800';
      case 'culture':
        return 'bg-blue-100 text-blue-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  };

  const getThemeIcon = (theme: string) => {
    switch (theme) {
      case 'nature':
        return '🌿';
      case 'history':
        return '🏛️';
      case 'food':
        return '🍽️';
      case 'culture':
        return '🎭';
      default:
        return '📖';
    }
  };

  const formatDate = (date: Date) => {
    return new Intl.DateTimeFormat('ko-KR', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    }).format(date);
  };

  const getItemTypeIcon = (type: string) => {
    switch (type) {
      case 'stamp':
        return '🏷️';
      case 'photo':
        return '📷';
      case 'video':
        return '🎥';
      case 'text':
        return '📝';
      default:
        return '📄';
    }
  };

  const handleLike = () => {
    setIsLiked(!isLiked);
    onLike?.(album);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      whileHover={{ y: -4 }}
      transition={{ duration: 0.2 }}
    >
      <Card
        className={`relative overflow-hidden transition-all duration-300 hover:shadow-xl ${
          isHovered ? 'scale-105' : 'scale-100'
        }`}
        onMouseEnter={() => setIsHovered(true)}
        onMouseLeave={() => setIsHovered(false)}
      >
        {/* 커버 이미지 */}
        <div className="relative h-48 overflow-hidden">
          {album.coverImageUrl ? (
            <Image
              src={album.coverImageUrl}
              alt={album.title}
              fill
              className="object-cover transition-transform duration-300 hover:scale-110"
            />
          ) : (
            <div className="w-full h-full bg-gradient-to-br from-blue-50 to-purple-50 flex items-center justify-center">
              <div className="text-6xl opacity-50">
                {getThemeIcon(album.theme)}
              </div>
            </div>
          )}

          {/* 오버레이 */}
          <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent" />

          {/* 테마 배지 */}
          <div className="absolute top-3 left-3">
            <Badge className={getThemeColor(album.theme)}>
              {getThemeIcon(album.theme)} {album.theme.toUpperCase()}
            </Badge>
          </div>

          {/* 자동 생성 배지 */}
          {album.isAutoGenerated && (
            <div className="absolute top-3 right-3">
              <Badge variant="secondary" className="bg-blue-100 text-blue-800">
                <Star className="h-3 w-3 mr-1" />
                자동 생성
              </Badge>
            </div>
          )}

          {/* 공개/비공개 배지 */}
          <div className="absolute bottom-3 right-3">
            <Badge variant={album.isPublic ? 'default' : 'outline'}>
              {album.isPublic ? '공개' : '비공개'}
            </Badge>
          </div>
        </div>

        <CardHeader className="pb-2">
          <CardTitle className="text-lg font-semibold text-gray-900 line-clamp-2">
            {album.title}
          </CardTitle>
          <p className="text-sm text-gray-600 line-clamp-2">
            {album.description}
          </p>
        </CardHeader>

        <CardContent className="space-y-3">
          {/* 통계 정보 */}
          <div className="flex items-center justify-between text-sm text-gray-500">
            <div className="flex items-center gap-4">
              <div className="flex items-center gap-1">
                <ImageIcon className="h-4 w-4" />
                <span>{album.itemCount}개</span>
              </div>
              <div className="flex items-center gap-1">
                <Eye className="h-4 w-4" />
                <span>{album.viewCount}</span>
              </div>
              <div className="flex items-center gap-1">
                <Heart className="h-4 w-4" />
                <span>{album.likeCount}</span>
              </div>
            </div>
            <div className="flex items-center gap-1">
              <Calendar className="h-4 w-4" />
              <span>{formatDate(album.createdAt)}</span>
            </div>
          </div>

          {/* 아이템 타입 미리보기 */}
          {album.items && album.items.length > 0 && (
            <div className="flex items-center gap-2 text-sm text-gray-500">
              <span>포함된 콘텐츠:</span>
              <div className="flex items-center gap-1">
                {album.items.slice(0, 3).map((item, index) => (
                  <span key={index} className="text-lg">
                    {getItemTypeIcon(item.type)}
                  </span>
                ))}
                {album.items.length > 3 && (
                  <span className="text-xs">+{album.items.length - 3}</span>
                )}
              </div>
            </div>
          )}

          {/* 액션 버튼 */}
          {showActions && (
            <div className="flex gap-2 pt-2">
              <Button
                variant="outline"
                size="sm"
                onClick={() => onView?.(album)}
                className="flex-1"
              >
                <Eye className="h-4 w-4 mr-2" />
                보기
              </Button>
              <Button
                variant="outline"
                size="sm"
                onClick={handleLike}
                className={`${isLiked ? 'text-red-500' : ''}`}
              >
                <Heart className={`h-4 w-4 ${isLiked ? 'fill-current' : ''}`} />
              </Button>
              <Button
                variant="outline"
                size="sm"
                onClick={() => onShare?.(album)}
              >
                <Share2 className="h-4 w-4" />
              </Button>
              <Button
                variant="outline"
                size="sm"
                onClick={() => onEdit?.(album)}
              >
                <MoreHorizontal className="h-4 w-4" />
              </Button>
            </div>
          )}
        </CardContent>

        {/* 호버 효과 */}
        {isHovered && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent rounded-lg flex items-end justify-center pb-4"
          >
            <div className="text-white text-sm font-medium bg-black/50 px-3 py-1 rounded-full">
              앨범 보기
            </div>
          </motion.div>
        )}
      </Card>
    </motion.div>
  );
}
